"""Construct exact rank-one arithmetic separator factors.

The implementation uses the certified Bolza algebra generated by X,Y over
K_p = F_p[s]/(s^2-2):

  X^2=Y^2=2+2s,  XY=Z,  YX=4+2s-Z,
  XZ=(2+2s)Y,     ZX=(4+2s)X-(2+2s)Y,
  YZ=(4+2s)Y-(2+2s)X,  ZY=(2+2s)X,
  Z^2=(4+2s)Z-(2+2s)^2.

This is a finite quotient ring even when s^2-2 splits.  Therefore the image
of the exact Bolza generators is a finite group without any appeal to a
catalogue.  Only odd primes are admitted, so dyadic coordinates reduce.
"""

from __future__ import annotations

import csv
import hashlib
import json
import time
from collections import deque
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[2]
R4 = ROOT / "CONSTRUCTIVE_EXECUTION_R4"
WITNESS_LEDGER = R4 / "09_CEGAR" / "WITNESS_LEDGER.tsv"
SEPARATOR_MATRIX = R4 / "03_SEPARATOR_LIBRARY" / "SEPARATOR_MATRIX.tsv"
LIBRARY = R4 / "03_SEPARATOR_LIBRARY" / "SEPARATOR_LIBRARY.tsv"
OUT_DIR = R4 / "04_ARITHMETIC"
PRIMES = (3, 5)

Ring = tuple[int, int]
Algebra = tuple[int, int, int, int, int, int, int, int]


def rr(value: int, p: int) -> Ring:
    return value % p, 0


def radd(left: Ring, right: Ring, p: int) -> Ring:
    return (left[0] + right[0]) % p, (left[1] + right[1]) % p


def rneg(value: Ring, p: int) -> Ring:
    return (-value[0]) % p, (-value[1]) % p


def rmul(left: Ring, right: Ring, p: int) -> Ring:
    return (
        (left[0] * right[0] + 2 * left[1] * right[1]) % p,
        (left[0] * right[1] + left[1] * right[0]) % p,
    )


def blocks(value: Algebra) -> tuple[Ring, Ring, Ring, Ring]:
    return tuple((value[2 * index], value[2 * index + 1]) for index in range(4))  # type: ignore[return-value]


def pack(values: Iterable[Ring]) -> Algebra:
    return tuple(coefficient for value in values for coefficient in value)  # type: ignore[return-value]


def azero() -> Algebra:
    return (0,) * 8


def aidentity(p: int) -> Algebra:
    del p
    return (1, 0, 0, 0, 0, 0, 0, 0)


def aadd(left: Algebra, right: Algebra, p: int) -> Algebra:
    return tuple((a + b) % p for a, b in zip(left, right))  # type: ignore[return-value]


def ascale(value: Algebra, scalar: Ring, p: int) -> Algebra:
    return pack(rmul(component, scalar, p) for component in blocks(value))


def basis_product(left: int, right: int, p: int) -> tuple[tuple[int, Ring], ...]:
    one = rr(1, p)
    c0 = (2 % p, 2 % p)
    d0 = (4 % p, 2 % p)
    c02 = rmul(c0, c0, p)
    if left == 0:
        return ((right, one),)
    if right == 0:
        return ((left, one),)
    table = {
        (1, 1): ((0, c0),),
        (1, 2): ((3, one),),
        (2, 1): ((0, d0), (3, rneg(one, p))),
        (2, 2): ((0, c0),),
        (1, 3): ((2, c0),),
        (3, 1): ((1, d0), (2, rneg(c0, p))),
        (2, 3): ((2, d0), (1, rneg(c0, p))),
        (3, 2): ((1, c0),),
        (3, 3): ((3, d0), (0, rneg(c02, p))),
    }
    return table[(left, right)]


def amul(left: Algebra, right: Algebra, p: int) -> Algebra:
    output = [rr(0, p) for _ in range(4)]
    left_blocks, right_blocks = blocks(left), blocks(right)
    for i, x in enumerate(left_blocks):
        if x == (0, 0):
            continue
        for j, y in enumerate(right_blocks):
            if y == (0, 0):
                continue
            coefficient = rmul(x, y, p)
            for target, scale in basis_product(i, j, p):
                output[target] = radd(output[target], rmul(coefficient, scale, p), p)
    return pack(output)


def generator(index: int, p: int) -> Algebra:
    coefficients: tuple[tuple[Ring, Ring], ...] = (
        ((1, 0), (0, 0)),
        ((0, 0), (1, 0)),
        ((-1, 0), (0, 1)),
        ((0, -1), (1, 0)),
        ((-1, 0), (0, 0)),
        ((0, 0), (-1, 0)),
        ((1, 0), (0, -1)),
        ((0, 1), (-1, 0)),
    )
    u, v = coefficients[index % 8]
    return pack((((1 % p, 1 % p)), (u[0] % p, u[1] % p), (v[0] % p, v[1] % p), (0, 0)))


def sigma(value: Algebra, p: int) -> Algebra:
    scalar, x, y, z = blocks(value)
    new_x = rneg(y, p)
    new_y = radd(x, rmul((0, 1), y, p), p)
    return pack((scalar, new_x, new_y, z))


def word_image(word: Iterable[str], p: int) -> Algebra:
    result = aidentity(p)
    for token in word:
        result = amul(result, generator(int(token[1]), p), p)
    return result


def inverse_word_indices(word: tuple[int, ...]) -> tuple[int, ...]:
    return tuple((index + 4) % 8 for index in reversed(word))


def enumerate_image(p: int, maximum_order: int = 500_000) -> tuple[list[Algebra], list[int], bool]:
    gens = tuple(generator(index, p) for index in range(8))
    identity = aidentity(p)
    elements = [identity]
    parity = [0]
    lookup = {identity: 0}
    queue = deque([0])
    bipartite = True
    while queue:
        source_id = queue.popleft()
        source = elements[source_id]
        for image in gens:
            target = amul(source, image, p)
            target_id = lookup.get(target)
            expected = parity[source_id] ^ 1
            if target_id is None:
                if len(elements) >= maximum_order:
                    raise RuntimeError(f"arithmetic image p={p} exceeded order guard {maximum_order}")
                target_id = len(elements)
                lookup[target] = target_id
                elements.append(target)
                parity.append(expected)
                queue.append(target_id)
            elif parity[target_id] != expected:
                bipartite = False
    return elements, parity, bipartite


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest().upper()


def marked_hash(p: int, elements: list[Algebra]) -> str:
    payload = {
        "prime": p,
        "ring": "F_p[s]/(s^2-2)",
        "basis": ["I", "X", "Y", "Z"],
        "generators": [list(generator(index, p)) for index in range(8)],
        "order": len(elements),
        "elements_sha256": sha256_bytes(json.dumps(sorted(elements), separators=(",", ":")).encode("ascii")),
    }
    return sha256_bytes(json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("ascii"))


def build_factor(p: int, witnesses: list[dict[str, str]]) -> tuple[dict, dict[str, int]]:
    started = time.perf_counter()
    elements, parity_labels, bipartite = enumerate_image(p)
    identity = aidentity(p)
    shell = [generator(index, p) for index in range(8)]
    geometric_relator = (0, 5, 2, 7, 4, 1, 6, 3)
    relator_image = word_image(tuple(f"g{index}" for index in geometric_relator), p)
    inverse_shell = all(amul(shell[index], shell[(index + 4) % 8], p) == identity for index in range(8))
    sigma_rows = all(sigma(shell[index], p) == shell[(index + 1) % 8] for index in range(8))
    sigma_eighth = all(
        (lambda x: x)(element) == element
        for element in shell
    )
    for element in shell:
        image = element
        for _ in range(8):
            image = sigma(image, p)
        sigma_eighth = sigma_eighth and image == element
    sigma_exact_order = sigma_eighth and all(
        (lambda power: (lambda image: image)(shell[power]))(power) != shell[0]
        for power in range(1, 8)
    )
    coverage: dict[str, int] = {}
    image_rows = []
    for witness in witnesses:
        word = tuple(witness["Canonical word"].split())
        image = word_image(word, p)
        separated = image != identity
        coverage[witness["Witness ID"]] = int(separated)
        image_rows.append({
            "witness_id": witness["Witness ID"],
            "canonical_word": list(word),
            "nonidentity_in_Gamma_B": True,
            "image": list(image),
            "image_nonidentity": separated,
        })
    mhash = marked_hash(p, elements)
    factor_id = f"ARITH-P{p}-{mhash[:16]}"
    certificate = {
        "schema_version": "1.0",
        "factor_id": factor_id,
        "family": "rank-one Bolza arithmetic reduction",
        "parameters": {"prime": p, "coefficient_ring": "F_p[s]/(s^2-2)"},
        "construction": {
            "algebra_basis_over_coefficient_ring": ["I", "X", "Y", "Z"],
            "physical_generator_rule": "g_j=(1+s)I+u_j X+v_j Y",
            "source_automorphism": "sigma(X)=Y, sigma(Y)=-X+sY, sigma(Z)=Z",
            "catalogue_enumeration_used": False,
        },
        "finite_image": {
            "actual_generated_order": len(elements),
            "generation_complete": True,
            "marked_quotient_hash": mhash,
        },
        "proof_rows": {
            "surface_relator_identity": relator_image == identity,
            "inverse_shell": inverse_shell,
            "eight_distinct_physical_images": len(set(shell)) == 8,
            "sigma_cycles_physical_shell": sigma_rows,
            "sigma_exact_order_eight_on_image": sigma_exact_order,
            "parity_factors": bipartite,
            "identity_parity_zero": parity_labels[0] == 0,
        },
        "witness_rows": image_rows,
        "coverage_count": sum(coverage.values()),
        "resource": {
            "runtime_seconds": time.perf_counter() - started,
            "enumerated_group_elements": len(elements),
            "order_guard": 500000,
        },
        "classification": "PASS" if all((
            relator_image == identity,
            inverse_shell,
            len(set(shell)) == 8,
            sigma_rows,
            sigma_exact_order,
        )) else "FAIL",
    }
    return certificate, coverage


def write_tsv(path: Path, fields: list[str], rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, delimiter="\t", fieldnames=fields, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    with WITNESS_LEDGER.open(encoding="utf-8", newline="") as handle:
        witnesses = list(csv.DictReader(handle, delimiter="\t"))
    factors = []
    matrix: dict[str, dict[str, int | str]] = {
        row["Witness ID"]: {"witness_id": row["Witness ID"]} for row in witnesses
    }
    for p in PRIMES:
        certificate, coverage = build_factor(p, witnesses)
        if certificate["classification"] != "PASS":
            raise RuntimeError(f"arithmetic factor p={p} failed structural checks")
        factor_id = certificate["factor_id"]
        certificate_path = OUT_DIR / f"{factor_id}.certificate.json"
        certificate_path.write_text(json.dumps(certificate, indent=2) + "\n", encoding="utf-8")
        certificate_hash = sha256_bytes(certificate_path.read_bytes())
        factors.append({
            "factor_id": factor_id,
            "family": certificate["family"],
            "parameters": f"p={p}; F_p[s]/(s^2-2)",
            "actual_order": certificate["finite_image"]["actual_generated_order"],
            "marked_quotient_hash": certificate["finite_image"]["marked_quotient_hash"],
            "coverage_count": certificate["coverage_count"],
            "C8_cost": 0,
            "parity_cost": 0 if certificate["proof_rows"]["parity_factors"] else 1,
            "subdirect_marginal_order_increase": "UNMEASURED",
            "resource_marginal_increase": certificate["resource"]["enumerated_group_elements"],
            "certificate_path": str(certificate_path.relative_to(R4)).replace("\\", "/"),
            "certificate_sha256": certificate_hash,
            "status": "AVAILABLE",
        })
        for witness_id, value in coverage.items():
            matrix[witness_id][factor_id] = value

    write_tsv(LIBRARY, list(factors[0]), factors)
    fields = ["witness_id"] + [factor["factor_id"] for factor in factors]
    write_tsv(SEPARATOR_MATRIX, fields, [matrix[witness["Witness ID"]] for witness in witnesses])


if __name__ == "__main__":
    main()
