#include <algorithm>
#include <array>
#include <cstdint>
#include <iostream>
#include <queue>
#include <set>
#include <stdexcept>
#include <string>
#include <unordered_set>
#include <vector>

// Exhaustive SL(2,25) x C2 direct-orbit family enumerator.  Field and
// semilinear conventions match enumerate_psl2_25_family_exact_gpt56sol.cpp;
// SL matrices themselves are not projectivized, so the central lift is kept.
namespace{
using Mat=std::array<std::uint8_t,4>;
struct F{std::array<std::array<std::uint8_t,25>,25>a{},m{};std::array<std::uint8_t,25>n{},iv{},fr{};F(){for(int x=0;x<25;++x){int x0=x%5,x1=x/5;n[x]=(-x0+5)%5+5*((-x1+5)%5);for(int y=0;y<25;++y){int y0=y%5,y1=y/5;a[x][y]=(x0+y0)%5+5*((x1+y1)%5);m[x][y]=(x0*y0+3*x1*y1)%5+5*((x0*y1+x1*y0)%5);}}for(int x=1;x<25;++x)for(int y=1;y<25;++y)if(m[x][y]==1){iv[x]=y;break;}for(int x=0;x<25;++x)fr[x]=power(x,5);}std::uint8_t power(std::uint8_t x,unsigned e)const{std::uint8_t r=1;while(e){if(e&1)r=m[r][x];x=m[x][x];e>>=1;}return r;}std::uint8_t det(const Mat&x)const{return a[m[x[0]][x[3]]][n[m[x[1]][x[2]]]];}Mat raw_product(const Mat&x,const Mat&y)const{return{a[m[x[0]][y[0]]][m[x[1]][y[2]]],a[m[x[0]][y[1]]][m[x[1]][y[3]]],a[m[x[2]][y[0]]][m[x[3]][y[2]]],a[m[x[2]][y[1]]][m[x[3]][y[3]]]};}Mat raw_inverse(const Mat&x)const{auto s=iv[det(x)];return{m[x[3]][s],m[n[x[1]]][s],m[n[x[2]]][s],m[x[0]][s]};}Mat norm(Mat x)const{auto it=std::find_if(x.begin(),x.end(),[](auto z){return z;});if(it==x.end())throw std::runtime_error("zero");auto s=iv[*it];for(auto&z:x)z=m[z][s];return x;}Mat proj_product(const Mat&x,const Mat&y)const{return norm(raw_product(x,y));}Mat sigma(Mat x)const{for(auto&z:x)z=fr[z];return x;}};
std::uint32_t pack(const Mat&x){return x[0]|(std::uint32_t(x[1])<<5)|(std::uint32_t(x[2])<<10)|(std::uint32_t(x[3])<<15);}
struct Semi{Mat c;std::uint8_t k;};bool operator==(const Semi&a,const Semi&b){return a.k==b.k&&a.c==b.c;}Semi compose(const F&f,const Semi&a,const Semi&b){return{f.proj_product(a.c,a.k?f.sigma(b.c):b.c),std::uint8_t((a.k+b.k)&1)};}Mat act(const F&f,const Semi&a,const Mat&x){auto y=a.k?f.sigma(x):x;return f.raw_product(f.raw_product(a.c,y),f.raw_inverse(a.c));}unsigned order(const F&f,const Semi&a){Semi p{{1,0,0,1},0};for(unsigned n=1;n<=64;++n){p=compose(f,a,p);if(p==Semi{{1,0,0,1},0})return n;}return 0;}
std::size_t b3(const F&f,const std::array<Mat,8>&g){std::set<std::uint64_t>s;s.insert(std::uint64_t(pack(Mat{1,0,0,1}))<<1);for(int a=0;a<8;++a){s.insert((std::uint64_t(pack(g[a]))<<1)|1U);for(int b=0;b<8;++b)if(b!=(a+4)%8){auto ab=f.raw_product(g[a],g[b]);s.insert(std::uint64_t(pack(ab))<<1);for(int c=0;c<8;++c)if(c!=(b+4)%8)s.insert((std::uint64_t(pack(f.raw_product(ab,g[c])))<<1)|1U);}}return s.size();}std::size_t generated(const F&f,const std::array<Mat,8>&g){std::unordered_set<std::uint32_t>s;std::queue<Mat>q;Mat id{1,0,0,1};s.insert(pack(id));q.push(id);while(!q.empty()){auto x=q.front();q.pop();for(auto&a:g){auto y=f.raw_product(x,a);if(s.insert(pack(y)).second)q.push(y);}}return s.size();}std::string show(const Mat&x){return"("+std::to_string(x[0])+","+std::to_string(x[1])+","+std::to_string(x[2])+","+std::to_string(x[3])+")";}
}
int main(){try{F f;Mat id{1,0,0,1};std::set<std::uint32_t>pk;std::vector<Mat>P,SL;for(int a=0;a<25;++a)for(int b=0;b<25;++b)for(int c=0;c<25;++c)for(int d=0;d<25;++d){Mat x{(std::uint8_t)a,(std::uint8_t)b,(std::uint8_t)c,(std::uint8_t)d};auto determinant=f.det(x);if(!determinant)continue;pk.insert(pack(f.norm(x)));if(determinant==1)SL.push_back(x);}for(auto k:pk)P.push_back(Mat{std::uint8_t(k&31),std::uint8_t((k>>5)&31),std::uint8_t((k>>10)&31),std::uint8_t((k>>15)&31)});if(P.size()!=15600||SL.size()!=15600)throw std::runtime_error("orders");const std::array<Semi,2>A{{{{0,1,5,9},0},{{0,1,5,5},1}}};std::uint64_t o8=0;for(int k=0;k<2;++k)for(auto c:P)o8+=(order(f,Semi{c,(std::uint8_t)k})==8);if(o8!=5200)throw std::runtime_error("automorphism count");std::uint64_t sum=0;
 for(int cls=0;cls<2;++cls){auto alpha=A[cls];std::vector<Semi>C;for(int k=0;k<2;++k)for(auto c:P){Semi z{c,(std::uint8_t)k};if(compose(f,alpha,z)==compose(f,z,alpha))C.push_back(z);}sum+=31200/C.size();std::uint64_t ni=0,nr=0,nd=0,nb=0,ng=0;std::vector<Mat>S;for(auto x:SL){std::array<Mat,8>g{};g[0]=x;for(int i=1;i<8;++i)g[i]=act(f,alpha,g[i-1]);bool ok=true;for(int i=0;i<4;++i)ok&=(g[i+4]==f.raw_inverse(g[i]));if(!ok)continue;++ni;auto r=id;for(int i:std::array<int,8>{0,5,2,7,4,1,6,3})r=f.raw_product(r,g[i]);if(r!=id)continue;++nr;if(std::set<Mat>(g.begin(),g.end()).size()!=8)continue;++nd;if(b3(f,g)!=457)continue;++nb;if(generated(f,g)!=15600)continue;++ng;S.push_back(x);}std::cout<<"CLASS "<<cls<<" centralizer="<<C.size()<<" class_size="<<31200/C.size()<<" seeds=15600 inverse="<<ni<<" relator="<<nr<<" distinct="<<nd<<" b3="<<nb<<" generates="<<ng<<'\n';std::set<Mat>left(S.begin(),S.end());unsigned oi=0;while(!left.empty()){auto rep=*left.begin();std::set<Mat>orb;for(auto&z:C)orb.insert(act(f,z,rep));for(auto&y:orb)left.erase(y);std::cout<<"ORBIT "<<oi++<<" size="<<orb.size()<<" rep="<<show(rep)<<'\n';}}
 if(sum!=o8)throw std::runtime_error("class exhaustion");std::cout<<"AUT order=31200 order8="<<o8<<" class_sum="<<sum<<'\n';return 0;}catch(const std::exception&e){std::cerr<<"ERROR: "<<e.what()<<'\n';return 2;}}
