#include <algorithm>
#include <array>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <queue>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <vector>
namespace{
constexpr int D=15;struct P{std::array<std::uint8_t,D>x{};bool operator==(const P&)const=default;};
P id(){P r;for(int i=0;i<D;++i)r.x[i]=i;return r;}P mul(const P&a,const P&b){P r;for(int i=0;i<D;++i)r.x[i]=a.x[b.x[i]];return r;}P inv(const P&a){P r;for(int i=0;i<D;++i)r.x[a.x[i]]=i;return r;}P cj(const P&t,const P&ti,const P&a){return mul(mul(t,a),ti);}std::uint64_t pk(const P&p){std::uint64_t r=0;for(int i=0;i<D;++i)r|=std::uint64_t(p.x[i])<<(4*i);return r;}std::uint64_t rk(const P&p){std::uint64_t r=0;for(int i=0;i<D;++i){unsigned d=0;for(int j=i+1;j<D;++j)d+=p.x[j]<p.x[i];r=r*(D-i)+d;}return r;}P unrk(std::uint64_t r){std::array<unsigned,D>d{};for(int i=D-1;i>=0;--i){unsigned b=D-i;d[i]=r%b;r/=b;}if(r)throw std::runtime_error("rank range");std::vector<unsigned>a;for(int i=0;i<D;++i)a.push_back(i);P p;for(int i=0;i<D;++i){p.x[i]=a.at(d[i]);a.erase(a.begin()+d[i]);}return p;}P tau(){auto t=id();for(int i=0;i<7;++i)t.x[i]=i+1;t.x[7]=0;for(int i=8;i<11;++i)t.x[i]=i+1;t.x[11]=8;std::swap(t.x[12],t.x[13]);return t;}void pp(const P&p){std::cout<<'[';for(int i=0;i<D;++i)std::cout<<(i?",":"")<<unsigned(p.x[i]);std::cout<<']';}
struct M{std::uint32_t parent;std::uint8_t generator,depth;std::uint16_t reserved;};static_assert(sizeof(M)==8);std::vector<M>tree(const std::string&f){std::ifstream in(f,std::ios::binary);if(!in)throw std::runtime_error("open tree");char m[8]{};std::uint64_t n=0;std::uint32_t s=0;in.read(m,8);in.read(reinterpret_cast<char*>(&n),8);in.read(reinterpret_cast<char*>(&s),4);if(std::string(m,8)!="BOLZAT01"||n!=23129593ULL||s!=8)throw std::runtime_error("tree drift");std::vector<M>v(n);in.read(reinterpret_cast<char*>(v.data()),v.size()*sizeof(M));if(!in)throw std::runtime_error("short tree");return v;}
struct G{std::vector<P>e;std::unordered_map<std::uint64_t,std::uint16_t>ix;std::array<std::vector<std::uint16_t>,8>tr;};G group(const std::array<P,8>&g,std::size_t expected){G q;q.e.reserve(expected);q.ix.reserve(2*expected+1);q.e.push_back(id());q.ix.emplace(pk(id()),0);for(std::size_t h=0;h<q.e.size();++h)for(int j=0;j<8;++j){auto y=mul(q.e[h],g[j]);auto [it,fresh]=q.ix.emplace(pk(y),static_cast<std::uint16_t>(q.e.size()));if(fresh){q.e.push_back(y);if(q.e.size()>expected)throw std::runtime_error("order too large");}}if(q.e.size()!=expected)throw std::runtime_error("order mismatch");for(int j=0;j<8;++j){q.tr[j].resize(expected);for(std::size_t i=0;i<expected;++i)q.tr[j][i]=q.ix.at(pk(mul(q.e[i],g[j])));}return q;}
}
int main(int ac,char**av){try{if(ac!=2)throw std::runtime_error("usage: BASED_TREE");const std::array<std::uint64_t,8>r{{556480109803ULL,556480110205ULL,1092802234603ULL,1092802235005ULL,201539964523ULL,201539964925ULL,737583024666ULL,775746081354ULL}};const std::array<unsigned,8>ord{{36000,36000,36000,36000,36000,36000,38880,38880}};const std::array<unsigned,8>odd{{0,0,0,0,0,0,1,1}};auto t=tau(),ti=inv(t);std::cout<<"tau=";pp(t);std::cout<<'\n';std::array<std::array<P,8>,8>a{};for(int k=0;k<8;++k){a[k][0]=unrk(r[k]);if(rk(a[k][0])!=r[k])throw std::runtime_error("unrank");for(int j=1;j<8;++j)a[k][j]=cj(t,ti,a[k][j-1]);for(int j=0;j<4;++j)if(!(a[k][j+4]==inv(a[k][j])))throw std::runtime_error("inverse");auto z=id();for(int j:std::array<int,8>{0,5,2,7,4,1,6,3})z=mul(z,a[k][j]);if(!(z==id()))throw std::runtime_error("relator");std::cout<<"candidate="<<k<<" rank="<<r[k]<<" odd_sign="<<odd[k]<<" expected_actual="<<ord[k]<<" expected_augmented="<<ord[k]<<" seed=";pp(a[k][0]);std::cout<<'\n';for(int j=0;j<8;++j){std::cout<<"candidate="<<k<<" g"<<j<<'=';pp(a[k][j]);std::cout<<'\n';}}std::cout.flush();auto tr=tree(av[1]);for(int k=0;k<8;++k){auto q=group(a[k],ord[k]);std::vector<std::uint16_t>st(tr.size());std::uint32_t w=0;for(std::uint32_t n=1;n<tr.size();++n){auto e=tr[n];if(e.parent>=n||e.generator>=8)throw std::runtime_error("edge");st[n]=q.tr[e.generator][st[e.parent]];if(!(e.depth&1U)&&st[n]==0){w=n;break;}}if(!w){std::cout<<"candidate="<<k<<" rank="<<r[k]<<" BASED_PASS\n";continue;}std::vector<unsigned>word;for(auto n=w;n;n=tr[n].parent)word.push_back(tr[n].generator);std::reverse(word.begin(),word.end());std::cout<<"candidate="<<k<<" rank="<<r[k]<<" based_witness_id="<<w<<" depth="<<unsigned(tr[w].depth)<<" word=";for(std::size_t i=0;i<word.size();++i)std::cout<<(i?" ":"")<<'g'<<word[i];std::cout<<'\n';std::cout.flush();}return 0;}catch(const std::exception&e){std::cerr<<"ERROR: "<<e.what()<<'\n';return 2;}}
