#include <algorithm>
#include <array>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <queue>
#include <set>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <vector>
namespace{
using M=std::array<std::uint8_t,9>;struct E{M a;std::uint8_t e;bool operator==(const E&)const=default;bool operator<(const E&o)const{return e<o.e||(e==o.e&&a<o.a);}};struct Meta{std::uint32_t parent;std::uint8_t generator,depth;std::uint16_t reserved;};static_assert(sizeof(Meta)==8);
int mod3(int x){x%=3;return x<0?x+3:x;}M idm(){return M{1,0,0,0,1,0,0,0,1};}int det(const M&a){return mod3(a[0]*(a[4]*a[8]-a[5]*a[7])-a[1]*(a[3]*a[8]-a[5]*a[6])+a[2]*(a[3]*a[7]-a[4]*a[6]));}M mul(const M&a,const M&b){M r{};for(int i=0;i<3;++i)for(int j=0;j<3;++j){int s=0;for(int k=0;k<3;++k)s+=a[3*i+k]*b[3*k+j];r[3*i+j]=mod3(s);}return r;}M inv(const M&a){int d=det(a),z=d==1?1:2;if(!d)throw std::runtime_error("singular");return M{(std::uint8_t)mod3(z*(a[4]*a[8]-a[5]*a[7])),(std::uint8_t)mod3(z*(a[2]*a[7]-a[1]*a[8])),(std::uint8_t)mod3(z*(a[1]*a[5]-a[2]*a[4])),(std::uint8_t)mod3(z*(a[5]*a[6]-a[3]*a[8])),(std::uint8_t)mod3(z*(a[0]*a[8]-a[2]*a[6])),(std::uint8_t)mod3(z*(a[2]*a[3]-a[0]*a[5])),(std::uint8_t)mod3(z*(a[3]*a[7]-a[4]*a[6])),(std::uint8_t)mod3(z*(a[1]*a[6]-a[0]*a[7])),(std::uint8_t)mod3(z*(a[0]*a[4]-a[1]*a[3]))};}M graph(const M&a){auto b=inv(a);return M{b[0],b[3],b[6],b[1],b[4],b[7],b[2],b[5],b[8]};}E product(const E&x,const E&y){return E{mul(x.a,x.e?graph(y.a):y.a),std::uint8_t(x.e^y.e)};}E inverse(const E&x){auto z=inv(x.a);return E{x.e?graph(z):z,x.e};}E conjugate(const E&h,const E&x){return product(product(h,x),inverse(h));}std::uint32_t mcode(const M&a){std::uint32_t r=0,p=1;for(auto x:a){r+=p*x;p*=3;}return r;}std::uint32_t code(const E&x){return mcode(x.a)|(std::uint32_t(x.e)<<15);}E decode(std::uint32_t c){E x{};x.e=(c>>15)&1;c&=32767;for(auto&z:x.a){z=c%3;c/=3;}return x;}
std::vector<Meta>load(const char*p){std::ifstream in(p,std::ios::binary);char mg[8]{};std::uint64_t n=0;std::uint32_t z=0;in.read(mg,8);in.read((char*)&n,8);in.read((char*)&z,4);if(!in||std::string(mg,8)!="BOLZAT01"||n!=23129593ULL||z!=8)throw std::runtime_error("tree contract");std::vector<Meta>v(n);in.read((char*)v.data(),n*8ULL);if(!in)throw std::runtime_error("short tree");return v;}
}
int main(int argc,char**argv){try{if(argc!=2)throw std::runtime_error("usage: scan_based_psl3_3_graph_extension_gpt56sol TREE");std::vector<M>S;for(std::uint32_t c=0;c<19683;++c){auto z=c;M a{};for(auto&x:a){x=z%3;z/=3;}if(det(a)==1)S.push_back(a);}std::vector<E>H;for(int e=0;e<2;++e)for(auto&a:S)H.push_back(E{a,(std::uint8_t)e});if(H.size()!=11232)throw std::runtime_error("target order");std::unordered_map<std::uint32_t,std::uint16_t>idx;for(std::size_t i=0;i<H.size();++i)idx.emplace(code(H[i]),(std::uint16_t)i);auto id=idx.at(code(E{idm(),0}));auto h=decode(33745);std::vector<E>C;for(auto&z:H)if(product(z,h)==product(h,z))C.push_back(z);if(C.size()!=8)throw std::runtime_error("centralizer size");const std::array<std::uint32_t,16>seed_codes{{34034,34070,34585,34778,35113,35466,36954,37286,37410,37922,38666,38898,41047,41276,42319,43748}};std::set<E>left;for(auto c:seed_codes)left.insert(decode(c));std::vector<E>reps;while(!left.empty()){auto r=*left.begin();std::set<E>orb;for(auto&z:C)orb.insert(conjugate(z,r));for(auto&x:orb)left.erase(x);std::cout<<"ORBIT size="<<orb.size()<<" rep_code="<<code(r)<<'\n';reps.push_back(r);}auto tree=load(argv[1]);for(auto seed:reps){std::array<E,8>g{};g[0]=seed;for(int i=1;i<8;++i)g[i]=conjugate(h,g[i-1]);std::array<std::vector<std::uint16_t>,8>next;for(int j=0;j<8;++j){next[j].resize(H.size());for(std::size_t i=0;i<H.size();++i)next[j][i]=idx.at(code(product(H[i],g[j])));}std::vector<std::uint16_t>state(tree.size());state[0]=id;std::uint32_t hit=0;for(std::uint32_t i=1;i<tree.size();++i){auto e=tree[i];state[i]=next[e.generator][state[e.parent]];if(state[i]==id){hit=i;break;}}std::cout<<"REP seed_code="<<code(seed);if(!hit){std::cout<<" BASED_PASS\n";continue;}std::vector<unsigned>w;for(auto i=hit;i;i=tree[i].parent)w.push_back(tree[i].generator);std::reverse(w.begin(),w.end());std::cout<<" witness_id="<<hit<<" depth="<<unsigned(tree[hit].depth)<<" word=";for(std::size_t i=0;i<w.size();++i)std::cout<<(i?" ":"")<<"g"<<w[i];std::cout<<'\n';}return 0;}catch(const std::exception&e){std::cerr<<"ERROR: "<<e.what()<<'\n';return 2;}}
