param([string]$BaseDir = ".")
$ErrorActionPreference = "Stop"
function Assert-Eq($A,$E,[string]$L){if([string]$A-ne[string]$E){throw "$L mismatch: actual=$A expected=$E"}}
function Parse-Pairs([string]$Line,[string]$Prefix,[int]$Start=1){$f=$Line-split"`t";if($f[0]-ne$Prefix-or(($f.Count-$Start)%2)-ne0){throw"malformed $Prefix: $Line"};$h=@{};for($i=$Start;$i-lt$f.Count;$i+=2){if($h.ContainsKey($f[$i])){throw"duplicate $($f[$i])"};$h[$f[$i]]=$f[$i+1]};return$h}
function Load-Map([string]$Name,[bool]$Sol){$m=@{};foreach($l in[IO.File]::ReadAllLines((Join-Path$BaseDir $Name))){if($l-notmatch'^ENTRY\t24T([0-9]+)\t'){continue};$k=[int]$Matches[1];$f=$l-split"`t";$h=@{};for($i=2;$i-lt$f.Count;$i+=2){$h[$f[$i]]=$f[$i+1]};$m[$k]=[pscustomobject]@{Order=[int64]$h.ORDER;Parity=[int64]$h.PARITY_MAPS;Solvable=if($Sol){[int]$h.SOLVABLE}else{$null}}};return$m}
function Keys($M,[int]$Lo,[int]$Hi){return@($M.Keys|%{[int]$_}|?{$_-ge$Lo-and$_-le$Hi}|Sort-Object)}
function Parse-Entry([string]$L){$f=$L-split"`t";if($f[0]-ne'ENTRY'-or$f[1]-notmatch'^24T([0-9]+)$'-or(($f.Count-2)%2)-ne0){throw"bad ENTRY: $L"};$k=[int]$Matches[1];$h=@{};for($i=2;$i-lt$f.Count;$i+=2){$h[$f[$i]]=$f[$i+1]};foreach($n in@('ORDER','SOLVABLE_G','PARITY_MAPS_G','PC_ORDER','PARITY_MAPS_P','AUT_ORDER','ISO_MS','AUT_MS','METHOD','CLASS_MS','ORDER8_CLASSES','RAW_PAIRS')){if(-not$h.ContainsKey($n)){throw"24T$k missing $n"}};return[pscustomobject]@{K=$k;Order=[int64]$h.ORDER;Solvable=$h.SOLVABLE_G;Parity=[int64]$h.PARITY_MAPS_G;PcOrder=[int64]$h.PC_ORDER;ParityP=[int64]$h.PARITY_MAPS_P;AutOrder=$h.AUT_ORDER;Iso=[int64]$h.ISO_MS;Aut=[int64]$h.AUT_MS;Method=$h.METHOD;Class=[int64]$h.CLASS_MS;Classes=[int64]$h.ORDER8_CLASSES;Raw=[int64]$h.RAW_PAIRS;Line=$L}}
$lo=12333;$hi=12595;$outName='GAP_TRANSITIVE_DEGREE24_AUT_PROFILE_12333_12595_PC_DOMAIN_RECOVERY_CHECKPOINT_GPT56SOL.txt';$stdoutName='GAP_TRANSITIVE_DEGREE24_AUT_PROFILE_SHARD14_RUN_STDOUT_GPT56SOL.txt';$stderrName='GAP_TRANSITIVE_DEGREE24_AUT_PROFILE_SHARD14_RUN_STDERR_GPT56SOL.txt';$wrapper='gap_run_degree24_aut_profile_shard14_12333_12595_pc_domain_gpt56sol.g'
$sol=Load-Map 'GAP_TRANSITIVE_DEGREE24_SOLVABILITY_10568_13274_GPT56SOL.txt' $true;$win=Load-Map 'GAP_TRANSITIVE_DEGREE24_PARITY_10568_13274_GPT56SOL.txt' $false;$expected=Keys $sol $lo $hi;$windowKeys=Keys $win $lo $hi
Assert-Eq $expected.Count 256 'sealed parity';Assert-Eq $windowKeys.Count 263 'sealed window';Assert-Eq @($expected|?{$sol[$_].Solvable-ne1}).Count 0 'sealed nonsolvable count';Assert-Eq ((Compare-Object $windowKeys $expected|?{$_.SideIndicator-eq'<='}|%{$_.InputObject})-join',') '12333,12453,12454,12455,12456,12459,12575' 'parity exclusions'
$lines=[IO.File]::ReadAllLines((Join-Path$BaseDir $outName));$header=@("CERTIFICATE_PROFILE`tPF-GRP-001-C8-TRANSITIVE-DEGREE24-AUT-PC-DOMAIN-RECOVERY-CHECKPOINT","GAP_VERSION`t4.12.1","DATABASE`t25000","RANGE`t12333`t12595","GUARD_MS`t1320000","EXPECTED_ORDER_WINDOW`t263","EXPECTED_PARITY`t256","SCOPE`tExact pc-isomorphic Aut(G), exact-order-8 conjugacy classes, and raw=Size(G)*class-count for solvable parity-capable order-window targets only; no seeds.","RECOVERY`tENTRY and CHECKPOINT certify each completed eligible key; SCAN_CHECKPOINT certifies every 25th completed catalogue key.");for($i=0;$i-lt$header.Count;$i++){Assert-Eq $lines[$i] $header[$i] "header $($i+1)"}
Assert-Eq @($lines|?{$_-match'^TOTAL\t'}).Count 1 'TOTAL count';Assert-Eq @($lines|?{$_-eq'DONE'}).Count 1 'DONE count';Assert-Eq $lines[-1] 'DONE' 'terminal';Assert-Eq @($lines|?{$_-match'^(TOTAL_PARTIAL|STOPPED_GUARD)'}).Count 0 'guard markers'
$entries=@();for($i=0;$i-lt$lines.Count;$i++){if($lines[$i]-match'^ENTRY\t'){$entries+=Parse-Entry $lines[$i]}};Assert-Eq $entries.Count 256 'entry count';Assert-Eq @($entries|Group-Object K|?{$_.Count-ne1}).Count 0 'duplicates';Assert-Eq @(Compare-Object $expected @($entries.K)).Count 0 'entry keyset'
[int64]$classes=0;[int64]$raw=0;[int64]$iso=0;[int64]$aut=0;[int64]$class=0;$prev=0
for($j=0;$j-lt$entries.Count;$j++){$e=$entries[$j];if($e.K-le$prev){throw"nonincreasing 24T$($e.K)"};$prev=$e.K;$s=$sol[$e.K];Assert-Eq $e.Order $s.Order "24T$($e.K) order";Assert-Eq $e.Solvable 'true' "24T$($e.K) solvable";Assert-Eq $e.Parity $s.Parity "24T$($e.K) parity";Assert-Eq $e.PcOrder $e.Order "24T$($e.K) pc order";Assert-Eq $e.ParityP $e.Parity "24T$($e.K) parity transport";Assert-Eq $e.Raw ($e.Order*$e.Classes) "24T$($e.K) raw";if($e.AutOrder-notmatch'^[1-9][0-9]*$'-or$e.Iso-lt0-or$e.Aut-lt0-or$e.Class-lt0-or$e.Method-notin@('pc','native')){throw"bad field 24T$($e.K)"};$classes+=$e.Classes;$raw+=$e.Raw;$iso+=$e.Iso;$aut+=$e.Aut;$class+=$e.Class;$idx=[Array]::IndexOf($lines,$e.Line);$cp=Parse-Pairs $lines[$idx+1] 'CHECKPOINT';Assert-Eq $cp.LAST_COMPLETE_K $e.K 'checkpoint key';Assert-Eq $cp.PROCESSED ($j+1) 'checkpoint processed';Assert-Eq $cp.ISO_MS $iso 'checkpoint iso';Assert-Eq $cp.ORDER8_CLASSES $classes 'checkpoint classes';Assert-Eq $cp.RAW_PAIRS $raw 'checkpoint raw'}
$scanKeys=@(12350,12375,12400,12425,12450,12475,12500,12525,12550,12575);$scans=@($lines|?{$_-match'^SCAN_CHECKPOINT\t'});Assert-Eq $scans.Count 10 'scan count';for($j=0;$j-lt10;$j++){$h=Parse-Pairs $scans[$j] 'SCAN_CHECKPOINT';$k=$scanKeys[$j];$p=@($entries|?{$_.K-le$k});Assert-Eq $h.LAST_COMPLETE_K $k 'scan key';Assert-Eq $h.ORDER_WINDOW (Keys $win $lo $k).Count 'scan window';Assert-Eq $h.PROCESSED $p.Count 'scan processed';Assert-Eq $h.ISO_MS ([int64](($p|Measure-Object Iso -Sum).Sum)) 'scan iso';Assert-Eq $h.ORDER8_CLASSES ([int64](($p|Measure-Object Classes -Sum).Sum)) 'scan classes';Assert-Eq $h.RAW_PAIRS ([int64](($p|Measure-Object Raw -Sum).Sum)) 'scan raw'}
$tl=@($lines|?{$_-match'^TOTAL\t'})[0];$pat='^TOTAL\tDEGREE\t24\tDATABASE\t25000\tRANGE\t12333\t12595\tLAST_COMPLETE_K\t12595\tORDER_WINDOW\t263\tPROCESSED\t256\tORDER8_CLASSES\t([0-9]+)\tRAW_PAIRS\t([0-9]+)\tISO_MS\t([0-9]+)\tAUT_MS\t([0-9]+)\tCLASS_MS\t([0-9]+)\tMS\t([0-9]+)$';if($tl-notmatch$pat){throw"bad TOTAL: $tl"};$g=$Matches;Assert-Eq $g[1] $classes 'total classes';Assert-Eq $g[2] $raw 'total raw';Assert-Eq $g[3] $iso 'total iso';Assert-Eq $g[4] $aut 'total aut';Assert-Eq $g[5] $class 'total class';$gapMs=[int64]$g[6]
Assert-Eq $classes 6265 'outcome classes';Assert-Eq $raw 123526656 'outcome raw';Assert-Eq $iso 222 'outcome iso';Assert-Eq $aut 73564 'outcome aut';Assert-Eq $class 77093 'outcome class';Assert-Eq $gapMs 158727 'outcome gap'
$stdout=[IO.File]::ReadAllText((Join-Path$BaseDir $stdoutName));$stderr=[IO.File]::ReadAllText((Join-Path$BaseDir $stderrName));Assert-Eq $stdout.Trim() "WROTE /mnt/d/work/revise/production_code/escalations/$outName" 'stdout';if($stderr-notmatch[regex]::Escape($wrapper)){throw'missing wrapper telemetry'};if($stderr-notmatch'Elapsed \(wall clock\) time \(h:mm:ss or m:ss\): ([^\r\n]+)'){throw'missing wall'};$wall=$Matches[1].Trim();Assert-Eq $wall '2:39.89' 'wall';if($stderr-notmatch'Maximum resident set size \(kbytes\): ([0-9]+)'){throw'missing RSS'};$rss=[int64]$Matches[1];Assert-Eq $rss 182400 'RSS';if($stderr-notmatch'Exit status: 0'){throw'bad exit'};if($rss-ge50331648){throw'RSS guard exceeded'}
$merged='GAP_TRANSITIVE_DEGREE24_AUT_PROFILE_12333_12595_MERGED_ROUTED_GPT56SOL.txt';$m=[Collections.Generic.List[string]]::new();$m.Add("CERTIFICATE_PROFILE`tPF-GRP-001-C8-TRANSITIVE-DEGREE24-AUT-SHARD14-MERGED-ROUTED");$m.Add("GAP_VERSION`t4.12.1");$m.Add("DATABASE`t25000");$m.Add("RANGE`t12333`t12595");$m.Add("ORDER_WINDOW`t263");$m.Add("PARITY_KEYS`t256");$m.Add("ROUTING`t12333..12595:pc;native-empty");$m.Add("SCOPE`tExact Aut/order-8 profile invariants only; no seed predicates.");foreach($e in$entries){$m.Add("ENTRY`t24T$($e.K)`tORDER`t$($e.Order)`tSOLVABLE_G`t$($e.Solvable)`tPARITY_MAPS`t$($e.Parity)`tREPRESENTATION`tpc_transport`tPC_ORDER`t$($e.PcOrder)`tAUT_ORDER`t$($e.AutOrder)`tISO_MS`t$($e.Iso)`tAUT_MS`t$($e.Aut)`tMETHOD`t$($e.Method)`tCLASS_MS`t$($e.Class)`tORDER8_CLASSES`t$($e.Classes)`tRAW_PAIRS`t$($e.Raw)")};$m.Add("TOTAL`tDEGREE`t24`tDATABASE`t25000`tRANGE`t12333`t12595`tORDER_WINDOW`t263`tPROCESSED`t256`tPC_TRANSPORT`t256`tNATIVE_NONSOLVABLE`t0`tORDER8_CLASSES`t$classes`tRAW_PAIRS`t$raw`tISO_MS`t$iso`tAUT_MS`t$aut`tCLASS_MS`t$class`tSEGMENT_GAP_MS`t$gapMs");$m.Add('DONE');[IO.File]::WriteAllLines((Join-Path$BaseDir $merged),$m,[Text.UTF8Encoding]::new($false))
$verify='GAP_TRANSITIVE_DEGREE24_AUT_PROFILE_SHARD14_VERIFY_GPT56SOL.txt';$v=@("CERTIFICATE_VERIFY`tPF-GRP-001-C8-TRANSITIVE-DEGREE24-AUT-PROFILE-SHARD14","RANGE`t12333`t12595","ORDER_WINDOW`t263","PARITY_KEYS`t256","ENTRY_KEYS_EXACT`tPASS","SOLVABLE_PC_ROUTE`t256`tPASS","NONSOLVABLE_NATIVE_ROUTE`t0`tPASS","PC_ORDER_PARITY_TRANSPORT`t256`tPASS","RAW_IDENTITIES`t256`tPASS","ENTRY_CHECKPOINT_PAIRS`t256`tPASS","SCAN_CHECKPOINTS`t10`tPASS","UNIQUE_TOTAL_DONE_NO_GUARD`tPASS","ORDER8_CLASSES`t$classes","RAW_PAIRS`t$raw","ISO_MS`t$iso","AUT_MS`t$aut","CLASS_MS`t$class","SEGMENT_GAP_MS`t$gapMs","WALL`t$wall","MAX_RSS_KB`t$rss","SEALED_KEYSETS_AND_STREAMS`tPASS","CANDIDATE_OR_SEED_PREDICATES`tNOT_RUN","VERIFY`tPASS","DONE");[IO.File]::WriteAllLines((Join-Path$BaseDir $verify),$v,[Text.UTF8Encoding]::new($false))
$ratio=[math]::Round(($aut+$class)/366714.0,6).ToString('0.000000',[Globalization.CultureInfo]::InvariantCulture);$rawRatio=[math]::Round($raw/197240832.0,6).ToString('0.000000',[Globalization.CultureInfo]::InvariantCulture);$agg='GAP_TRANSITIVE_DEGREE24_AUT_PROFILE_SHARD14_AGGREGATE_GPT56SOL.txt';$a=@("CERTIFICATE`tPF-GRP-001-C8-TRANSITIVE-DEGREE24-AUT-PROFILE-SHARD14","STATUS`tSHARD_COMPLETE_ROUTED_INDEPENDENTLY_VERIFIED","DEGREE`t24","DATABASE`t25000","RANGE`t12333`t12595","LAST_COMPLETE_K`t12595","ORDER_WINDOW`t263","PARITY_KEYS`t256","PARITY_EXCLUDED`t7","SEGMENTS`t12333..12595-pc;native-empty","PC_TRANSPORT_KEYS`t256","NATIVE_NONSOLVABLE_KEYS`t0","ORDER8_CLASSES`t$classes","RAW_PAIRS`t$raw","ISO_MS`t$iso","AUT_MS`t$aut","CLASS_MS`t$class","AUT_PLUS_CLASS_MS`t$($aut+$class)","SEGMENT_GAP_MS`t$gapMs","POINT_FORECAST_MS`t366714","ACTUAL_TO_POINT_RATIO`t$ratio","POINT_FORECAST_CLASSES`t10096","POINT_FORECAST_RAW_PAIRS`t197240832","ACTUAL_TO_RAW_POINT_RATIO`t$rawRatio","ENTRY_CHECKPOINT_PAIRS`t256","SCAN_CHECKPOINTS`t10","RAW_IDENTITIES_PASS`t256","PC_TRANSPORT_IDENTITIES_PASS`t256","CANDIDATE_OR_SEED_PREDICATES`tNOT_RUN","INTERNAL_GUARD_MS`t1320000","EXTERNAL_WALL_GUARD_SECONDS`t1400","WALL`t$wall","MAX_RSS_KB`t$rss","EXTERNAL_GUARD_EVENTS`t0","GUARD_TRIGGERED_FINAL_SEGMENT`t0","VERIFY`tPASS","SCOPE`tExact Aut(G), exact-order-8 conjugacy-class count, and raw=Size(G)*class-count for range 12333..12595 only. This is not full degree-24 closure and contains no seed test.","DONE");[IO.File]::WriteAllLines((Join-Path$BaseDir $agg),$a,[Text.UTF8Encoding]::new($false))
$cert='GAP_TRANSITIVE_DEGREE24_AUT_PROFILE_SHARD14_GPT56SOL_CERTIFICATE.md';$c=@('# Degree-24 exact Aut/order-8 profile - shard 14','','Status: **complete and independently verified for catalogue range `12333..12595` only**. This is not full degree-24 closure.','','The sealed evidence contains 263 order-window keys and 256 parity-capable keys. All 256 parity keys are solvable, so the exact maximal routing is one pc-domain segment over the whole catalogue range and an empty native segment. The seven parity-excluded keys are `12333`, `12453..12456`, `12459`, and `12575`; the scanner visits them but constructs no automorphism group for them.','','For each included key, an exact isomorphism from G to a pc group P induces an automorphism-group isomorphism by conjugation. It preserves automorphism order and conjugacy. GAP checks group order and the exact number of epimorphisms to C2 on both sides, so every class count and raw contribution is transported exactly.','',"Exact totals: 6,265 exact-order-8 classes; 123,526,656 raw pairs; ISO/AUT/class times 222/$aut/$class ms; GAP time $gapMs ms; wall $wall; peak RSS $rss KiB. All 256 entry/checkpoint pairs, 10 scan checkpoints, key sets, raw identities, transport identities, complete header, unique TOTAL, terminal DONE, stdout, stderr, guard status, and resource records pass.",'','No inverse, relator, B3, generation, centralizer-orbit, candidate, or other seed predicate was run. Shard 14 is sealed; shard 15 remains unrun.');[IO.File]::WriteAllLines((Join-Path$BaseDir $cert),$c,[Text.UTF8Encoding]::new($false))
Write-Output "PASS shard14 range=12333-12595 window=263 parity=256 pc=256 native=0 classes=$classes raw=$raw isoMs=$iso autMs=$aut classMs=$class gapMs=$gapMs wall=$wall maxRssKb=$rss"
