"""Freeze the terminal GLOBAL-UNRESOLVED certificate for the direct attempt."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
GROUP = ROOT / "production_code" / "group"
FORECAST = GROUP / "GLOBAL_DIRECT_RESOURCE_FORECAST.json"
PILOT = ROOT / "data" / "production" / "global_direct" / "pilot_cyclic_phi8.json"
JSON_OUT = GROUP / "GLOBAL_SYSTOLE_DIRECT_CERTIFICATE.json"
MD_OUT = GROUP / "GLOBAL_SYSTOLE_DIRECT_CERTIFICATE.md"


def main() -> None:
    forecast = json.loads(FORECAST.read_text(encoding="utf-8"))
    pilot = json.loads(PILOT.read_text(encoding="utf-8"))
    if pilot["explicit_witness"] is not None:
        classification = "GLOBAL-FAIL"
    else:
        classification = "GLOBAL-UNRESOLVED"
    axis = forecast["mathematical_complete_domains"]["axis_to_base_cell_reduction"]
    flood = forecast["large_search_estimates"]["axis_to_base_cell_flood"]
    record = {
        "schema_version": "1.0",
        "task_id": "PF-GRP-001-GEO-GLOBAL-DIRECT",
        "quotient_id": "Q_BASED_S4CORE_PAIR_001",
        "quotient_order_N": 11_943_936,
        "global_direct_search_attempted": True,
        "method": pilot["method"],
        "search_domain": {
            "completed": f"primitive geometric word lengths 1..{pilot['maximum_primitive_geometric_word_length']}, canonicalized by cyclic conjugacy, inversion, and C8",
            "raw_c8_normalized_leaves": sum(int(v) for v in pilot["raw_c8_normalized_leaves_by_length"].values()),
            "canonical_orbits": sum(int(v) for v in pilot["canonical_orbits_by_length"].values()),
            "dangerous_kernel_power_candidates": sum(int(v) for v in pilot["dangerous_kernel_power_candidates_by_length"].values()),
            "required_for_pass_word_bound": 110,
            "alternative_complete_based_radius_over_a_B": axis["required_based_displacement_radius_over_a_B"],
        },
        "proof_exhaustion": False,
        "classification": classification,
        "explicit_shortest_dangerous_kernel_witness": pilot["explicit_witness"],
        "certified_absence_scope": "No dangerous kernel power generated by a primitive geometric word of length at most 9 in the completed canonical pilot domain.",
        "global_systole_over_a_B": None,
        "r_inj_global_geo_over_a_B": None,
        "margin_above_Dc_over_a_B_3": None,
        "existing_quotient_promotion": "DENIED; PQ-14 and PQ-16 remain unresolved",
        "resource_use": {
            "pilot_runtime_seconds": float(pilot["runtime_seconds"]),
            "pilot_peak_ram_bytes": None,
            "pilot_peak_ram_note": "Not instrumented; depth-first pilot stores O(maximum word length) search state and a bounded result record.",
            "new_artifact_disk_bytes": FORECAST.stat().st_size + PILOT.stat().st_size,
            "forecast_total_physical_memory_bytes": forecast["host_at_forecast"]["total_physical_memory_bytes"],
            "forecast_available_physical_memory_bytes": forecast["host_at_forecast"]["available_physical_memory_bytes"],
            "estimated_complete_flood_states": flood["estimated_candidate_states"],
            "estimated_complete_flood_peak_memory_bytes": flood["estimated_peak_memory_bytes_at_measured_layout"],
            "estimated_complete_flood_csv_bytes": flood["estimated_csv_bytes_if_current_row_schema_is_retained"],
        },
        "alternatives_evaluated_in_order": forecast["alternative_method_audit_in_required_order"],
        "exact_primary_stop_condition": "No proof-complete Bolza conjugacy normal-form/trace automaton is registered, while the alternative exact axis-to-base-cell flood is estimated to require 511,608,849,632 bytes, exceeding the 68,112,736,256-byte host RAM.",
        "required_to_resume": "A proof-complete representative-emitting Bolza conjugacy/symbolic automaton with certified trace pruning, or an out-of-core exact flood design with a proved resource envelope for radius 7.60179185438737 a_B.",
        "based_certificate_recomputed": False,
        "full_bilayer_constructed": False,
        "main_tex_modified": False,
        "manuscript_pdf_generated": False,
    }
    JSON_OUT.write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")
    MD_OUT.write_text(
        "# Direct global-systole certificate for `Q_BASED_S4CORE_PAIR_001`\n\n"
        "## Terminal classification\n\n"
        "**GLOBAL-UNRESOLVED.** This is not a pass and does not promote the existing "
        "`N=11,943,936` based product quotient. PQ-14 and PQ-16 remain unresolved.\n\n"
        "## Completed quotient-specific search\n\n"
        f"The bounded pilot enumerated {record['search_domain']['raw_c8_normalized_leaves']:,} freely and cyclically reduced "
        f"leaves through geometric word length 9. Cyclic conjugacy, inversion, and the exact `C8` label action reduce these "
        f"to {record['search_domain']['canonical_orbits']:,} canonical orbits. For every orbit, the exact finite-image order "
        "was used to test the corresponding kernel power. No dangerous kernel power was found. This certifies only the "
        "declared length-9 pilot domain.\n\n"
        "## Complete-domain theorem and resource boundary\n\n"
        "If a dangerous kernel element has translation length at most `6 a_B`, conjugate one point of its axis into the "
        "base octagon. The conjugate then displaces the octagon center by at most `6 a_B + 2 r_out = "
        f"{axis['required_based_displacement_radius_over_a_B']:.14f} a_B`. Thus an exact Dirichlet--Voronoi flood through "
        "this radius would be complete. Scaling the frozen exact radius-6 enumeration by the hyperbolic disk-area ratio "
        f"predicts {flood['estimated_candidate_states']:,} states and {flood['estimated_peak_memory_bytes_at_measured_layout'] / 2**30:.2f} GiB "
        "of resident memory. The host has only 63.44 GiB total RAM, so that route is not authorized.\n\n"
        "The alternative length-110 raw-word route is also intractable. GAP, SageMath, and libgap are unavailable; the "
        "audited external trace table lacks representative words and a completeness proof; and no certified quotient-state "
        "trace-pruning automaton is registered. These are exact missing mathematical/computational objects, not a numerical "
        "nonconvergence claim.\n\n"
        "The based dangerous set was not recomputed, no bilayer Hamiltonian was built, and `main.tex` was not modified.\n",
        encoding="utf-8",
    )
    print(json.dumps({"classification": classification, "proof_exhaustion": False, "canonical_orbits": record["search_domain"]["canonical_orbits"]}, indent=2))


if __name__ == "__main__":
    main()
